name: build-and-publish
on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: pikalab/ci:jdk-gradle-git-graphviz
jobs:
  check-style:
    runs-on: ubuntu-latest
    name: Check code style
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Image
        run: docker build . -t $IMAGE_NAME

      - name: Login on Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push on Docker Hub
        run: docker push $IMAGE_NAME
